/**
 * Error codes for the change submission system
 * Organized by category for better maintainability
 */
const ERROR_CODES = {
  // Required Fields
  REQUIRED: {
    FIELD: 'REQUIRED_FIELD',
    RISK_LEVEL: 'REQUIRED_RISK_LEVEL',
    IMPLEMENTATION_DATE: 'REQUIRED_IMPLEMENTATION_DATE',
    CHANGE_WINDOW: 'REQUIRED_CHANGE_WINDOW',
    SME: 'REQUIRED_SME',
    CAB_APPROVAL: 'REQUIRED_CAB_APPROVAL',
    PEER_REVIEW: 'REQUIRED_PEER_REVIEW'
  },

  // Invalid Values
  INVALID: {
    IMPLEMENTATION_DATE: 'INVALID_IMPLEMENTATION_DATE',
    RISK_LEVEL: 'INVALID_RISK_LEVEL',
    CHANGE_WINDOW: 'INVALID_CHANGE_WINDOW',
    SME: 'INVALID_SME'
  },

  // Timer Related
  TIMER: {
    INVALID_START: 'INVALID_TIMER_START',
    INVALID_END: 'INVALID_TIMER_END',
    INVALID_DURATION: 'INVALID_TIMER_DURATION',
    OVERLAP: 'TIMER_OVERLAP',
    GAP: 'TIMER_GAP',
    OUT_OF_BOUNDS: 'TIMER_OUT_OF_BOUNDS',
    INVALID_FORMAT: 'TIMER_INVALID_FORMAT',
    MISSING: 'TIMER_MISSING',
    DUPLICATE: 'TIMER_DUPLICATE',
    INVALID_SEQUENCE: 'TIMER_INVALID_SEQUENCE'
  },

  // Content Length Warnings
  SHORT: {
    IMPLEMENTATION_PLAN: 'SHORT_IMPLEMENTATION_PLAN',
    BACKOUT_PLAN: 'SHORT_BACKOUT_PLAN',
    VALIDATION_PLAN: 'SHORT_VALIDATION_PLAN',
    COMMUNICATION_PLAN: 'SHORT_COMMUNICATION_PLAN',
    TESTING_REQUIREMENTS: 'SHORT_TESTING_REQUIREMENTS',
    SECURITY_CONSIDERATIONS: 'SHORT_SECURITY_CONSIDERATIONS',
    PERFORMANCE_IMPACT: 'SHORT_PERFORMANCE_IMPACT',
    COMPLIANCE_REQUIREMENTS: 'SHORT_COMPLIANCE_REQUIREMENTS',
    DOCUMENTATION_REQUIREMENTS: 'SHORT_DOCUMENTATION_REQUIREMENTS',
    TRAINING_REQUIREMENTS: 'SHORT_TRAINING_REQUIREMENTS',
    MAINTENANCE_REQUIREMENTS: 'SHORT_MAINTENANCE_REQUIREMENTS'
  },

  // Empty Fields
  EMPTY: {
    DEPENDENCIES: 'EMPTY_DEPENDENCIES',
    RESOURCES: 'EMPTY_RESOURCES'
  }
};

// Export the error codes
export default ERROR_CODES; 